# Generated by Django 4.1.5 on 2023-02-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
