# Generated by Django 4.1.5 on 2023-02-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPL', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libro',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Pelicula',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Serie',
        ),
    ]
