# Generated by Django 4.1.5 on 2023-04-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPL', '0003_remove_libro_sinopsis_remove_pelicula_sinopsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='sinopsis',
            field=models.TextField(default=0),
        ),
    ]
