# Generated by Django 4.1.5 on 2023-04-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPL', '0004_libro_sinopsis_pelicula_sinopsis_serie_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
